

CREATE TABLE EMPLOYEE (
  EMPLOYEE_NUMBER NUMBER(10,0) AUTO_INCREMENT,
  FIRST_NAME VARCHAR2(255) default '',
  LAST_NAME VARCHAR2(255) default '',
  TITLE VARCHAR2(255) default '',
  PHONE_NUMBER VARCHAR2(255) default '',
  EMAIL VARCHAR2(255) default '',
  HIRE_DATE VARCHAR2(255) default '',
  MANAGER varchar2(255) DEFAULT '',
  DEPARTMENT_NUMBER_DEPARTMENT_NUMBER NUMBER default '',
  PRIMARY KEY (EMPLOYEE_NUMBER)
);


DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (
  DEPARTMENT_NUMBER NUMBER(10,0) AUTO_INCREMENT,
  NAME VARCHAR2(255) default '',
  MANAGER varchar2(255) DEFAULT '',
  PRIMARY KEY (DEPARTMENT_NUMBER)
);

DROP SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence;